adb: Print `stderr` on negative status when capturing output
When capturing process output both `stdout` and `stderr` are collected
by Rust instead of forwarded to the console.  When such a command has a
non-zero exit code, at the very least emit `stderr` within the `anyhow`
error message so that users know what's up: for me it's typically:

    Error: adb getprop exited with code Some(1)

that now results in a more sensible:

    Error: adb getprop exited with code Some(1): adb: device '<id>' not found